# Generated by Django 4.1.7 on 2023-03-19 13:05

from django.db import migrations


def create_data(apps, schema_editor):
    User = apps.get_model('users', 'Users')
    User(name='Users', email="joe@email.com", phone="00000000").save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
